# Generated by Django 5.1.3 on 2025-02-24 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'ordering': ['-add_time']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
