# Generated by Django 5.1.3 on 2025-02-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_productrating_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_order_price',
        ),
    ]
