# Generated by Django 5.1.3 on 2025-03-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_order_options_orderitem_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_status',
            field=models.BooleanField(default=False),
        ),
    ]
