# Generated by Django 5.1.3 on 2025-03-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_order_received_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish_status',
        ),
    ]
