# Generated by Django 5.1.3 on 2025-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_product_demo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
