# Generated by Django 5.1.3 on 2025-03-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
