# Generated by Django 5.1.3 on 2025-04-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0037_message_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='contenttypes.contenttype'),
        ),
    ]
