# Generated by Django 5.1.3 on 2025-05-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cnic_back',
            field=models.ImageField(null=True, upload_to='seller_imgs/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='cnic_front',
            field=models.ImageField(null=True, upload_to='seller_imgs/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='cnic_number',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
