# Generated by Django 5.1.3 on 2025-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_seller_cnic_back_seller_cnic_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_doc',
            field=models.ImageField(null=True, upload_to='seller_imgs/'),
        ),
    ]
